### ISSUE TITLE
CT cannot read property 'hasConnection' of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#101]
```
build-a-molecule : fuzz : built : run
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'hasConnection' of undefined
TypeError: Cannot read property 'hasConnection' of undefined
    at H.value (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:922519)
    at C.getBondDirection (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:6736782)
    at new C (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:6881112)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:6883683
    at Array.map (<anonymous>)
    at new C (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:6883661)
    at C.value (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:6889662)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:6974157
    at H.value (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:117202)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:168313
id: Bayes Chrome
Approximately 10/3/2019, 4:04:34 AM
build-a-molecule : fuzz : built : run
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'a' of undefined
TypeError: Cannot read property 'a' of undefined
    at Function.C.getMoleculesFromBrokenBond (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:913016)
    at C.breakBond (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:6736532)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:6971162
    at Array.forEach (<anonymous>)
    at end (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:6971128)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:6966417
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:165787)
    at C.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:6967917)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:6967110)
    at H.value (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/build/phet/build-a-molecule_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1040:759389)
id: Bayes Chrome
Approximately 10/3/2019, 4:04:34 AM
build-a-molecule : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'hasConnection' of undefined
TypeError: Cannot read property 'hasConnection' of undefined
    at LewisDotModel.getBondDirection (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/model/LewisDotModel.js?:92:19)
    at Kit.getBondDirection (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/model/Kit.js?:322:33)
    at new MoleculeBondNode (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/view/MoleculeBondNode.js?:63:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/view/MoleculeBondContainerNode.js?:27:22
    at Array.map (<anonymous>)
    at new MoleculeBondContainerNode (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/view/MoleculeBondContainerNode.js?:26:39)
    at KitPlayAreaNode.addMoleculeBondNodes (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/view/KitPlayAreaNode.js?:63:39)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/view/BAMView.js?:107:36
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/axon/js/TinyEmitter.js?:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/axon/js/Emitter.js?:35:31
id: Bayes Chrome
Approximately 10/3/2019, 4:04:34 AM
build-a-molecule : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Could not find bond!
Error: Assertion failed: Could not find bond!
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/assert/js/assert.js:22:13)
    at Molecule.getBond (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/model/MoleculeStructure.js?:253:17)
    at Kit.breakBond (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/model/Kit.js?:306:99)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/view/SliceNode.js?:111:17
    at Array.forEach (<anonymous>)
    at end (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/view/SliceNode.js?:108:23)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/scenery/js/input/SimpleDragHandler.js?:206:26
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/axon/js/Action.js?:238:20)
    at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/scenery/js/input/SimpleDragHandler.js?:320:26)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/scenery/js/input/SimpleDragHandler.js?:263:16)
id: Bayes Chrome
Approximately 10/3/2019, 4:04:34 AM
build-a-molecule : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: Cannot read property 'hasConnection' of undefined
TypeError: Cannot read property 'hasConnection' of undefined
    at LewisDotModel.getBondDirection (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/model/LewisDotModel.js?:92:19)
    at Kit.getBondDirection (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/model/Kit.js?:322:33)
    at new MoleculeBondNode (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/view/MoleculeBondNode.js?:63:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/view/MoleculeBondContainerNode.js?:27:22
    at Array.map (<anonymous>)
    at new MoleculeBondContainerNode (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/view/MoleculeBondContainerNode.js?:26:39)
    at KitPlayAreaNode.addMoleculeBondNodes (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/view/KitPlayAreaNode.js?:63:39)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/view/BAMView.js?:107:36
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/axon/js/TinyEmitter.js?:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/axon/js/Emitter.js?:35:31
id: Bayes Chrome
Approximately 10/3/2019, 4:04:34 AM
build-a-molecule : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Could not find bond!
Error: Assertion failed: Could not find bond!
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/assert/js/assert.js:22:13)
    at Molecule.getBond (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/model/MoleculeStructure.js?:253:17)
    at Kit.breakBond (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/model/Kit.js?:306:99)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/view/SliceNode.js?:111:17
    at Array.forEach (<anonymous>)
    at end (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/build-a-molecule/js/view/SliceNode.js?:108:23)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/scenery/js/input/SimpleDragHandler.js?:206:26
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/axon/js/Action.js?:238:20)
    at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/scenery/js/input/SimpleDragHandler.js?:320:26)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1570097074349/scenery/js/input/SimpleDragHandler.js?:263:16)
id: Bayes Chrome
Approximately 10/3/2019, 4:04:34 AM
```

**Comment by pixelzoom** [comment]
Still a problem as of 10/11/19.

**Comment by Denz1994** [comment]
A check has been added for the existence of an `Atom` and its `hasConnection` attribute. CT is failing to report this bug any longer. Closing.
