### ISSUE TITLE
CT cannot read property atoms of null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#222]
```
build-a-molecule : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/build-a-molecule_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-molecule%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1612753303239%22%2C%22timestamp%22%3A1612755258010%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Uncaught TypeError: Cannot read property 'atoms' of null
TypeError: Cannot read property 'atoms' of null
at Function.getCombinedMoleculeFromBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/model/MoleculeStructure.js:524:10)
at Kit.getPossibleMoleculeStructureFromBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/model/Kit.js:581:30)
at Kit.canBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/model/Kit.js:671:42)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/model/Kit.js:611:47
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/model/Kit.js:600:18
at Array.forEach (<anonymous>)
at Kit.attemptToBondMolecule (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/model/Kit.js:597:20)
at Kit.atomDropped (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/model/Kit.js:220:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/view/BAMScreenView.js:437:20)
id: Bayes Chrome
Snapshot from 2/7/2021, 8:01:43 PM

----------------------------------

build-a-molecule : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/build-a-molecule_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-molecule%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1612753303239%22%2C%22timestamp%22%3A1612792500416%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Uncaught Error: Bond not found
Error: Bond not found
at LewisDotModel.getBondDirection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/model/LewisDotModel.js:116:11)
at Kit.getBondDirection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/model/Kit.js:340:31)
at new MoleculeBondNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/view/MoleculeBondNode.js:68:31)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/view/MoleculeBondContainerNode.js:24:14
at Array.map (<anonymous>)
at new MoleculeBondContainerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/view/MoleculeBondContainerNode.js:23:37)
at KitPlayAreaNode.addMoleculeBondNodes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/view/KitPlayAreaNode.js:90:39)
at addedMoleculeListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/view/BAMScreenView.js:165:30)
at addedEmitterListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/build-a-molecule/js/common/view/BAMScreenView.js:233:11)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612753303239/axon/js/TinyEmitter.js:71:18)
id: Bayes Chrome
Snapshot from 2/7/2021, 8:01:43 PM
```

**Comment by KatieWoe** [comment]
```
build-a-molecule : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/build-a-molecule/build-a-molecule_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-molecule%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648314385011%22%2C%22timestamp%22%3A1648320820295%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of null (reading 'atoms')
TypeError: Cannot read properties of null (reading 'atoms')
at Function.getCombinedMoleculeFromBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/MoleculeStructure.js:546:10)
at Kit.getPossibleMoleculeStructureFromBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:578:30)
at Kit.canBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:667:88)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:606:46
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:597:18
at Array.forEach (<anonymous>)
at Kit.attemptToBondMolecule (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:595:20)
at Kit.atomDropped (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:206:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/view/BAMScreenView.js:410:20)
id: Bayes Chrome
Snapshot from 3/26/2022, 11:06:25 AM

----------------------------------

build-a-molecule : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/build-a-molecule/build-a-molecule_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-molecule%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648314385011%22%2C%22timestamp%22%3A1648329182961%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of null (reading 'atoms')
TypeError: Cannot read properties of null (reading 'atoms')
at Function.getCombinedMoleculeFromBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/MoleculeStructure.js:546:10)
at Kit.getPossibleMoleculeStructureFromBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:578:30)
at Kit.canBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:667:88)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:606:46
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:597:18
at Array.forEach (<anonymous>)
at Kit.attemptToBondMolecule (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:595:20)
at Kit.atomDropped (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:206:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/view/BAMScreenView.js:410:20)
id: Bayes Chrome
Snapshot from 3/26/2022, 11:06:25 AM

----------------------------------

build-a-molecule : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/build-a-molecule/build-a-molecule_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-molecule%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648314385011%22%2C%22timestamp%22%3A1648417333793%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of null (reading 'atoms')
TypeError: Cannot read properties of null (reading 'atoms')
at Function.getCombinedMoleculeFromBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/MoleculeStructure.js:546:10)
at Kit.getPossibleMoleculeStructureFromBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:578:30)
at Kit.canBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:667:88)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:606:46
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:597:18
at Array.forEach (<anonymous>)
at Kit.attemptToBondMolecule (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:595:20)
at Kit.atomDropped (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:206:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/build-a-molecule/js/common/view/BAMScreenView.js:410:20)
id: Bayes Chrome
Snapshot from 3/26/2022, 11:06:25 AM
```
