### ISSUE TITLE
CT cannot read properties of undefined reading dragListener

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#225]
```
build-a-molecule : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/build-a-molecule/build-a-molecule_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-molecule%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1632138742661%22%2C%22timestamp%22%3A1632140750763%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of undefined (reading 'dragListener')
TypeError: Cannot read properties of undefined (reading 'dragListener')
at BAMScreenView.onAtomRemovedFromPlayArea (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/build-a-molecule/js/common/view/BAMScreenView.js:457:14)
at removeAtomNodeFromPlayArea (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/build-a-molecule/js/common/view/BAMScreenView.js:197:12)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/axon/js/TinyEmitter.js:86:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/axon/js/Emitter.js:39:24
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/axon/js/Emitter.js:64:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/axon/js/createObservableArray.js:151:86
at Array.forEach (<anonymous>)
at Object.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/axon/js/createObservableArray.js:151:44)
at Proxy.observableArray.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/axon/js/createObservableArray.js:203:28)
id: Bayes Chrome
Snapshot from 9/20/2021, 5:52:22 AM

----------------------------------

build-a-molecule : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/build-a-molecule/build-a-molecule_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-molecule%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1632138742661%22%2C%22timestamp%22%3A1632148376442%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Bond not found
Error: Bond not found
at LewisDotModel.getBondDirection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/build-a-molecule/js/common/model/LewisDotModel.js:116:11)
at Kit.getBondDirection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/build-a-molecule/js/common/model/Kit.js:340:31)
at new MoleculeBondNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/build-a-molecule/js/common/view/MoleculeBondNode.js:68:31)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/build-a-molecule/js/common/view/MoleculeBondContainerNode.js:24:14
at Array.map (<anonymous>)
at new MoleculeBondContainerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/build-a-molecule/js/common/view/MoleculeBondContainerNode.js:23:37)
at KitPlayAreaNode.addMoleculeBondNodes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/build-a-molecule/js/common/view/KitPlayAreaNode.js:90:39)
at addedMoleculeListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/build-a-molecule/js/common/view/BAMScreenView.js:165:30)
at addedEmitterListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/build-a-molecule/js/common/view/BAMScreenView.js:233:11)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 9/20/2021, 5:52:22 AM
```

**Comment by KatieWoe** [comment]
Occurs reading other things as well. Example:
```
build-a-molecule : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/build-a-molecule/build-a-molecule_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-molecule%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1639554961947%22%2C%22timestamp%22%3A1639558579115%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of null (reading 'atoms')
TypeError: Cannot read properties of null (reading 'atoms')
at Function.getCombinedMoleculeFromBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/model/MoleculeStructure.js:546:10)
at Kit.getPossibleMoleculeStructureFromBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:578:30)
at Kit.canBond (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:667:88)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:606:46
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:597:18
at Array.forEach (<anonymous>)
at Kit.attemptToBondMolecule (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:595:20)
at Kit.atomDropped (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:206:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/view/BAMScreenView.js:410:20)
id: Bayes Chrome
Snapshot from 12/15/2021, 12:56:01 AM

----------------------------------

build-a-molecule : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/build-a-molecule/build-a-molecule_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-molecule%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1639554961947%22%2C%22timestamp%22%3A1639575946371%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Bond not found
Error: Bond not found
at LewisDotModel.getBondDirection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/model/LewisDotModel.js:122:11)
at Kit.getBondDirection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/model/Kit.js:329:31)
at new MoleculeBondNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/view/MoleculeBondNode.js:62:31)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/view/MoleculeBondContainerNode.js:22:14
at Array.map (<anonymous>)
at new MoleculeBondContainerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/view/MoleculeBondContainerNode.js:21:37)
at KitPlayAreaNode.addMoleculeBondNodes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/view/KitPlayAreaNode.js:77:39)
at addedMoleculeListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/view/BAMScreenView.js:148:30)
at addedEmitterListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/build-a-molecule/js/common/view/BAMScreenView.js:217:11)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
id: Bayes Chrome
Snapshot from 12/15/2021, 12:56:01 AM
```
