### ISSUE TITLE
CT Arc startAngle should be a finite number: NaN

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#93]
```
build-a-molecule : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: Arc startAngle should be a finite number: NaN
Error: Assertion failed: Arc startAngle should be a finite number: NaN
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1558050882766/assert/js/assert.js:22:13)
    at EllipticalArc.invalidate (https://bayes.colorado.edu/continuous-testing/snapshot-1558050882766/kite/js/segments/EllipticalArc.js?bust=1558076410485:384:17)
    at new EllipticalArc (https://bayes.colorado.edu/continuous-testing/snapshot-1558050882766/kite/js/segments/EllipticalArc.js?bust=1558076410485:60:10)
    at Molecule3DNode.draw (https://bayes.colorado.edu/continuous-testing/snapshot-1558050882766/build-a-molecule/js/view/view3d/Molecule3DNode.js?bust=1558076410485:304:29)
    at Molecule3DNode.tick (https://bayes.colorado.edu/continuous-testing/snapshot-1558050882766/build-a-molecule/js/view/view3d/Molecule3DNode.js?bust=1558076410485:344:12)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1558050882766/axon/js/TinyEmitter.js?bust=1558076410485:58:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558050882766/axon/js/Emitter.js?bust=1558076410485:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1558050882766/axon/js/Action.js?bust=1558076410485:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1558050882766/axon/js/Emitter.js?bust=1558076410485:61:20)
    at CollectionList.step (https://bayes.colorado.edu/continuous-testing/snapshot-1558050882766/build-a-molecule/js/screens/BAMScreen.js?bust=1558076410485:37:21)
id: Bayes Chrome
Approximately 5/16/2019, 5:54:42 PM
```

**Comment by KatieWoe** [comment]
```build-a-molecule : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Arc startAngle should be a finite number: NaN
Error: Assertion failed: Arc startAngle should be a finite number: NaN
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1570010302444/assert/js/assert.js:22:13)
    at EllipticalArc.invalidate (https://bayes.colorado.edu/continuous-testing/snapshot-1570010302444/kite/js/segments/EllipticalArc.js?:384:17)
    at new EllipticalArc (https://bayes.colorado.edu/continuous-testing/snapshot-1570010302444/kite/js/segments/EllipticalArc.js?:60:10)
    at Molecule3DNode.draw (https://bayes.colorado.edu/continuous-testing/snapshot-1570010302444/build-a-molecule/js/view/view3d/Molecule3DNode.js?:304:29)
    at Molecule3DNode.tick (https://bayes.colorado.edu/continuous-testing/snapshot-1570010302444/build-a-molecule/js/view/view3d/Molecule3DNode.js?:344:12)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1570010302444/axon/js/TinyEmitter.js?:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570010302444/axon/js/Emitter.js?:35:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1570010302444/axon/js/Action.js?:238:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1570010302444/axon/js/Emitter.js?:60:21)
    at KitCollectionList.step (https://bayes.colorado.edu/continuous-testing/snapshot-1570010302444/build-a-molecule/js/model/KitCollectionList.js?:46:24)
id: Bayes Chrome
Approximately 10/2/2019, 3:58:22 AM
```

**Comment by Denz1994** [comment]
This is related to https://github.com/phetsims/build-a-molecule/issues/103. We can close this issue.
